name: 'gh-sync Action'
description: 'Run gh-sync to synchronize GitHub issues with ADO tracking'
inputs:
  ado-organization-url:
    description: 'Fully qualified URL to the Azure DevOps organization (e.g. https://dev.azure.com/organization/)'
    required: true
  ado-project:
    description: 'The name of the ADO project'
    required: true
  ado-area-path:
    description: 'The backlog area that new ADO items will be created in (e.g. <Your Project>/<Area>)'
    required: true
  github-repo:
    description: 'The full GitHub repository path (e.g. <GitHub Organization>/<GitHub Project>)'
    required: true
  issue-number:
    description: 'The issue number supplied from the triggered GitHub workflow'
    required: true
  ado-token:
    description: 'The Personal Access Token (PAT) associated with your Azure Devops account'
    required: true
  github-token:
    description: 'The authentication token for GitHub such as a PAT or secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ado-organization-url }}
    - ${{ inputs.ado-project }}
    - ${{ inputs.ado-area-path }}
    - ${{ inputs.github-repo }}
    - ${{ inputs.issue-number }}
    - ${{ inputs.ado-token }}
    - ${{ inputs.github-token }}