name: 'gh-sync Action'
description: 'Run gh-sync to synchronize GitHub issues with ADO tracking'
inputs:
  ado-project-url:
    description: 'Fully qualified URL to the Azure DevOps organization including the project name (e.g. https://dev.azure.com/organization/project-name)'
    required: true
  ado-collection-url:
    description: 'Fully qualified URL to the Azure Devops organization (e.g. https://dev.azure.com/organization/)'
    required: true
  github-repo:
    description: 'The full GitHub repository path (e.g. microsoft/QuantumKatas)'
    required: true
  issue-number:
    description: 'The issue number supplied from the triggered GitHub workflow'
    required: true
  ado-token:
    description: 'The Personal Access Token (PAT) associated with your Azure Devops account'
    required: true
  github-token:
    description: 'The authentication token for GitHub, supplied as secrets.GITHUB_TOKEN by default'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ado-collection-url }}
    - ${{ inputs.ado-project-url }}
    - ${{ inputs.github-repo }}
    - ${{ inputs.issue-number }}
    - ${{ inputs.ado-token }}
    - ${{ inputs.github-token }}