trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 6.0.101
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'AzureRM / Solid'
    KeyVaultName: 'kv-qdk-build'
    SecretsFilter: 'GitHubPAT'
    RunAsPreJob: false
    
- task: PowerShell@2
  displayName: 'Install and Run'
  inputs:
    targetType: 'inline'
    script: |
      ./install.ps1
      gh-sync pull-all-gh microsoft/$(repoName) --dry-run
  env:
    ADO_TOKEN: $(ADO_TOKEN)
    GITHUB_TOKEN: $(GitHubPAT)
