# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 6.0.101
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
- task: PowerShell@2
  displayName: 'Install'
  inputs:
    targetType: 'inline'
    script: |
      ./install.ps1

- task: PowerShell@2
  displayName: 'Run'
  inputs:
    targetType: 'inline'
    script: |
      gh-sync pull-all-gh microsoft/quantumkatas --dry-run
  env:
    ADO_TOKEN: $(ADO_TOKEN)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
