# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.402
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
- task: PowerShell@2
  inputs:
    filePath: './install.ps1'

# - powershell: |
#     gh-sync pull-gh microsoft/iqsharp 567 --dry-run
#   displayName: 'Run script'
#   workingDirectory: '$(System.DefaultWorkingDirectory)'